version: 0.2
phases:
  install:
    runtime-versions:
      docker: latest
  pre_build:
    commands:
      # Set the appropriate Dockerrun file name based on pipeline and branch
      - echo getting env Logging in to Amazon ECR... PIPELINE_NAME= $PIPELINE_NAME

      - cp Dockerrun-prod.aws.json Dockerrun.aws.json

      - echo Logging in to Amazon ECR...
      - aws --region $AWS_DEFAULT_REGION ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose --file=docker-compose-prod.yml build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose --file=docker-compose-prod.yml push
artifacts:
  files:
    - 'Dockerrun.aws.json'
