version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      SIGNATURE_KEY_D: ${SIGNATURE_KEY_D}
      SIGNATURE_KEY_X: ${SIGNATURE_KEY_X}
      SIGNATURE_KEY_Y: ${SIGNATURE_KEY_Y}
      CERT_SECRET_KEY: ${CERT_SECRET_KEY}
      APP_PORT: 3200
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - '3200:3200'
    networks:
      - creator_credentials_dev
  
networks:
  creator_credentials_dev:
    driver: bridge
