version: 2
updates:
  - package-ecosystem: pnpm
    target-branch: 'develop'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - 'kd-leo'
    groups:
      prod-dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'
