export const QueryKeys = {
  creatorVerifiedCredentials: 'creatorVerifiedCredentials',
  creatorEmailCredential: 'creatorEmailCredential',
  creatorIssuers: 'creatorIssuers',
  creatorIssuerDetails: 'creatorIssuerDetails',
  issuersByCredentials: 'issuersByCredentials',
  requestableCredentials: 'requestableCredentials',
  issuerCredentials: 'issuerCredentials',
  issuerCreators: 'issuerCreators',
  credentialsRequestDetails: 'credentialsRequestDetails',
  issuerProfile: 'issuerProfile',
  generateNonce: 'generateNonce',
  issuersCredentials: 'issuersCredentials',
  getUser: 'getUser',
  getIssuers: 'getIssuers',
  creatorsRequestableTemplates: 'creatorsRequestableTemplates',
};
